language: python
python:
  - "2.7"
addons:
  postgresql: "9.1"
virtualenv:
  system_site_packages: true
before_install:
install: 
  - pip install  --allow-external --allow-unverified -r requirements.txt
  - cd reports/static && npm install
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres 
script: 
  - grunt bowercopy && grunt test --retries 1
  - cd ../../ 
  - python manage.py migrate contenttypes --settings=lims.travis-settings
  - python manage.py migrate sites --settings=lims.travis-settings
  - python manage.py migrate auth --settings=lims.travis-settings 
  - python manage.py migrate admin --settings=lims.travis-settings
  - python manage.py migrate sessions --settings=lims.travis-settings  
  - python manage.py migrate tastypie --settings=lims.travis-settings
  - python manage.py migrate reports --settings=lims.travis-settings
  - python manage.py migrate db 0001 --settings=lims.travis-settings
#  - python manage.py migrate db 0020 --fake --settings=lims.travis-settings
  - python manage.py test --settings=lims.travis-settings --verbosity=2


