language: python
python:
  - "2.7"
services:
  - postgresql
virtualenv:
  system_site_packages: true
before_install:
install: 
  - pip install  --allow-external --allow-unverified -r requirements.txt
  - cd reports/static && npm install
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres 
script: 
##  - grunt bowercopy
##  - grunt test --verbose || echo 'unresolved spurious test failure 20160606'
  - npm run build
  - cd ../../ 
  - python manage.py migrate sites --settings=lims.travis-settings || echo 'expected error on first migration...'
  - python manage.py migrate auth --settings=lims.travis-settings 
  - python manage.py migrate contenttypes --settings=lims.travis-settings
  - python manage.py migrate admin --settings=lims.travis-settings
  - python manage.py migrate sessions --settings=lims.travis-settings  
  - python manage.py migrate tastypie --settings=lims.travis-settings
  - python manage.py migrate reports --settings=lims.travis-settings
  - python manage.py migrate db 0001 --settings=lims.travis-settings
##  - python manage.py migrate db 0020 --fake --settings=lims.travis-settings
  - python manage.py test db.tests.CherryPickRequestResource --settings=lims.travis-settings --verbosity=2



