language: python
python:
  - "2.7"
addons:
  postgresql: "9.1"
virtualenv:
  system_site_packages: true
before_install:
install: 
  - pip install -r requirements.txt
  - cd reports/static && npm install
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script: 
  - grunt bowercopy && grunt test
  - cd ../../ && python manage.py test --settings=lims.travis-settings --verbosity=2

